version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=mysql+pymysql://user:password@db/rc_db
    volumes:
      - .:/app
    depends_on:
      flyway:
        condition: service_completed_successfully
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=rc_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_PUBLIC_KEY_PATH=/var/lib/mysql/public_key.pem
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  flyway:
      image: flyway/flyway
      command: -url="jdbc:mysql://db/rc_db?allowPublicKeyRetrieval=true" -user=user -password=password -connectRetries=60 migrate
      volumes:
        - ./sql:/flyway/sql
      depends_on:
        db:
          condition: service_healthy
      networks:
        - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge